# Generated by Django 4.1.7 on 2023-03-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_terminmonth_loanrequest_term_in_months_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['due_date']},
        ),
    ]
