# Generated by Django 4.1.7 on 2023-03-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_installment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loanprovider')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
